### ISSUE TITLE
HTMLSanitizer Question

### ISSUE THREAD

**Issue by multimokia** [EmitKnowledge/Signals#48]
Hi there I was leveraging a few DTOs with the framework but noticed a common issue in that not all html was being cleaned up by the sanitizer's built-in methods.

I do see that the sanitizer _does_ allow us to set allowed attributes, but this is something that needs to be done in a per-dto basis. Is there a way to assign this globally?

**Comment by mnikolovski** [comment]
By design we are setting this up intentionally to avoid security issues with XSS injection. At the moment Signals only supports exclusions per DTO basis.

**Comment by mnikolovski** [comment]
By design we are setting this up intentionally to avoid security issues with XSS injection. At the moment Signals only supports exclusions per DTO basis.
