### ISSUE TITLE
Documentation is Outdated

### ISSUE THREAD

**Issue by multimokia** [EmitKnowledge/Signals#49]
https://github.com/EmitKnowledge/Signals/blob/4e392b3896cc2b65419c914c60784b3e31d57b54/src/10%20Core/Signals.Core/Processes/Api/ApiProcessAttribute.cs#L57

I forgot I had to dig into source for this but according to this change the documentation listed in the Wiki is outdated as it uses an outdated `ApiProcess` attribute, however, looks like this was changed sometime before 2021 to `SignalsApi` with a custom HttpMethod definition.

**Comment by mnikolovski** [comment]
The API attribute is used to decorate the API Endpoint and define it's behaviour.
We are starting to work on a new documentation which will be much better than the one we are having now.

**Comment by mnikolovski** [comment]
I will close this issue for now.
